"""empty message

Revision ID: 23bb8c2a8c65
Revises: 
Create Date: 2023-05-19 09:44:29.013111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bb8c2a8c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species'))
    )
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_title'), ['title'], unique=True)

    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_animals_species_id_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animals'))
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_animals_species_id'), ['species_id'], unique=False)

    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_sightings_species_id_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sightings'))
    )
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sightings_species_id'), ['species_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sightings_species_id'))

    op.drop_table('sightings')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_species_id'))
        batch_op.drop_index(batch_op.f('ix_animals_name'))

    op.drop_table('animals')
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_title'))

    op.drop_table('species')
    # ### end Alembic commands ###
